### ISSUE TITLE
velodyne  demo failed 

### ISSUE THREAD

**Issue by hitbg-yjm** [hku-mars/BALM#1]
Do you know the problem in the picture?

 /home/yjm/BALM_ws/src/BALM/src/myso3/myso3.cpp:20: SO3::SO3(const Quaterniond&): Assertion `unit_quaternion_.squaredNorm() > SMALL_EPS' failed
![Screenshot from 2020-11-17 10-20-00](https://user-images.githubusercontent.com/64351196/99338116-8f6b4000-28be-11eb-8794-80a0a80e461b.png)

**Comment by Saki-Chen** [comment]
I get this error too when the sensor move fast.

**Comment by hitbg-yjm** [comment]
It seems right , especially in the case of rotation.

**Comment by Zale-Liu** [comment]
Is it a new velodyne bag?

**Comment by hitbg-yjm** [comment]
Yes

**Comment by Zale-Liu** [comment]
> Yes

Can you upload it on onedrive or google drive? Then share the link with me. So I can debug it on my own computer. E-mail is also OK. Thank you.

**Comment by hitbg-yjm** [comment]
It is from autoware

Download the sample data (LiDAR: VELODYNE HDL-32E, GNSS: JAVAD GPS RTK Delta 3) in ROSBAG format or ROSBAG2 format.

 wget https://autoware-ai.s3.us-east-2.amazonaws.com/sample_moriyama_150324.tar.gz

**Comment by Zale-Liu** [comment]
> It is from autoware
> 
> Download the sample data (LiDAR: VELODYNE HDL-32E, GNSS: JAVAD GPS RTK Delta 3) in ROSBAG format or ROSBAG2 format.
> 
> wget https://autoware-ai.s3.us-east-2.amazonaws.com/sample_moriyama_150324.tar.gz

![32](https://user-images.githubusercontent.com/66358657/99797465-463f1880-2b6a-11eb-8b66-cbf1cffa66a7.png)
I have run your bag. The problem is that our new "scan2map" module runs fast but is not robust enough. It may fail when moving fast. With a robust scan2map, the result can be better like the picture. The BALM now is just a demo to show how the BA works instead of a complete slam work. We will fix the problem in the next version and give a complete slam framework.

**Comment by hitbg-yjm** [comment]
> he problem is that our new "scan2map" module runs fast but is not robust enough. It may fail when moving fast. With a robust scan2map, the result can be better like the

OK，I am going to close the issue  and look forward to the next version.
