### ISSUE TITLE
Why Second order approximation

### ISSUE THREAD

**Issue by dysenustc** [hku-mars/BALM#9]
Hi, i have a question about the slide window ba, why you choose second order approximation eigenvalues w.r.t poses?
I try to use first order approximation to solve this problem, but the iteration result cannot converge. Is this ba formulation converge region is small?

**Comment by Zale-Liu** [comment]
The cost function for second-order Newton iteration method and Gauss-Newton iteration method are different. The eigen value is equal to the square of distance. If you use Gauss-Newton method, it mean you optimize the fourth power of distance, that's why the convergence is very slow. But if you use second-order Newton method, the optimization variable is the square of disstance. It generally needs 4 or 5 iterations to converge.

**Comment by dysenustc** [comment]
ok, thank you very much
